spring.application.name=know-your-money
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://localhost:5432/kymdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.show-sql=true
spring.liquibase.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true