CREATE TABLE TRANSACTIONS  (
	TRANSACTION_ID BIGINT  NOT NULL PRIMARY KEY ,
	TRANSACTION_DATE TIMESTAMP NOT NULL,
	TRANSACTION_DETAILS VARCHAR(1000),
	TRANSACTION_REFERENCE VARCHAR(100),
	VALUE_DATE TIMESTAMP NOT NULL,
	WITHDRAW_AMOUNT NUMERIC(10,2),
	DEPOSIT_AMOUNT NUMERIC(10,2),
	CLOSING_BALANCE NUMERIC(10,2)
) ;